# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v2

    - name: dynamically retrieve go version
      uses: arnested/go-version-action@v1
      id: go-version

    - name: setup go ${{ steps.go-version.outputs.minimal }}
      uses: actions/setup-go@v2
      with: 
        go-version: ${{ steps.go-version.outputs.minimal }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
